version: '3'
services:
  oacis:
    # image: oacis_test #image: oacis/oacis_jupyter
    build:
      context: oacis_docker/oacis
      dockerfile: Dockerfile
    volumes:
      - ./Result:/home/oacis/oacis/public/Result_development
      - ${HOME}/.ssh/config:/home/oacis/.ssh/config:ro
    environment:
      - LOCAL_UID
      - LOCAL_GID
      - LOCAL_USER
    #env_file: ./.env
    ports:
      - "127.0.0.1:${OACIS_PORT:-3000}:3000"
      - "127.0.0.1:${JUPYTER_PORT:-8888}:8888"
    tty: true
